-- Cache for expensive shadow calculations.
-- One row represents one outdoor venue at one rounded time bucket.

create table if not exists public.bar_shadow_cache (
  id bigint generated by default as identity primary key,
  outdoor_seating_place_id bigint unique not null
    references public.outdoor_seating_places (id)
    on delete cascade,

  -- Round calculation time to a fixed interval, e.g. 15 minutes.
  calculated_for timestamptz not null,
  cache_bucket_minutes smallint not null default 15,

  lat numeric(10,7) not null,
  lon numeric(10,7) not null,
  shadow_test_lat numeric(10,7),
  shadow_test_lon numeric(10,7),
  shadow_test_point_source text,

  in_shadow boolean,
  shadow_reason text,
  shadow_error text,

  building_count_fetched integer,
  building_count_used integer,
  nearest_building_distance_m numeric(8,1),
  farthest_used_building_distance_m numeric(8,1),

  sun_elevation_deg numeric(6,2),
  sun_azimuth_deg numeric(6,2),

  blocking_building_id bigint,
  blocking_building_height_m numeric(8,2),
  blocking_building_distance_m numeric(8,1),
  blocking_building_shadow_length_m numeric(8,1),

  -- Keep the full raw result too, so the Python shape can change without a
  -- migration every time.
  shadow_payload jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint bar_shadow_cache_unique_bucket unique (
    outdoor_seating_place_id,
    calculated_for,
    cache_bucket_minutes
  ),
  constraint bar_shadow_cache_lat_range check (lat between -90 and 90),
  constraint bar_shadow_cache_lon_range check (lon between -180 and 180),
  constraint bar_shadow_cache_bucket_positive check (cache_bucket_minutes > 0)
);

create index if not exists bar_shadow_cache_place_time_idx
  on public.bar_shadow_cache (outdoor_seating_place_id, calculated_for desc);

create index if not exists bar_shadow_cache_calculated_for_idx
  on public.bar_shadow_cache (calculated_for desc);

create index if not exists bar_shadow_cache_in_shadow_idx
  on public.bar_shadow_cache (in_shadow)
  where in_shadow is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_bar_shadow_cache_updated_at on public.bar_shadow_cache;
create trigger set_bar_shadow_cache_updated_at
before update on public.bar_shadow_cache
for each row
execute function public.set_updated_at();

-- Public read access is useful if the frontend needs cached shadow data.
-- Inserts/updates should happen server-side or from local scripts with a service role key.
alter table public.bar_shadow_cache enable row level security;

drop policy if exists "Public bar shadow cache read access" on public.bar_shadow_cache;
create policy "Public bar shadow cache read access"
  on public.bar_shadow_cache
  for select
  using (true);

comment on table public.bar_shadow_cache is
  'Cached shadow results for outdoor seating places.';
comment on column public.bar_shadow_cache.calculated_for is
  'UTC time rounded to a cache bucket, for example 2026-05-21 10:15:00+00.';
comment on column public.bar_shadow_cache.shadow_payload is
  'Full raw shadow result from the Python shadow calculation.';
