-- Supabase/Postgres schema for outdoor_seating_places.csv.
-- Column names match the CSV header, so Supabase CSV import can map them directly.

create table if not exists public.outdoor_seating_places (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  lat numeric(10,7) not null,
  lon numeric(10,7) not null,
  coordinate_source text not null,
  outdoor_seating boolean not null,
  outdoor_seating_source text not null,
  category text not null,
  osm_type text not null,
  osm_id bigint not null,
  osm_name text,
  osm_address text,
  osm_outdoor_seating_raw text,
  google_place_id text,
  google_name text,
  google_address text,
  google_outdoor_seating boolean,
  google_price_level text,
  google_price_range jsonb,
  google_rating numeric(2,1),
  google_user_rating_count integer,
  google_maps_uri text,
  google_match_distance_m numeric(6,1),
  google_match_name_similarity numeric(4,3),
  imported_at timestamptz not null default now(),

  constraint outdoor_seating_places_osm_unique unique (osm_type, osm_id),
  constraint outdoor_seating_places_lat_range check (lat between -90 and 90),
  constraint outdoor_seating_places_lon_range check (lon between -180 and 180),
  constraint outdoor_seating_places_rating_range check (
    google_rating is null or google_rating between 0 and 5
  ),
  constraint outdoor_seating_places_similarity_range check (
    google_match_name_similarity is null
    or google_match_name_similarity between 0 and 1
  )
);

create index if not exists outdoor_seating_places_name_idx
  on public.outdoor_seating_places using gin (to_tsvector('simple', name));

create index if not exists outdoor_seating_places_category_idx
  on public.outdoor_seating_places (category);

create index if not exists outdoor_seating_places_google_place_id_idx
  on public.outdoor_seating_places (google_place_id)
  where google_place_id is not null;

create index if not exists outdoor_seating_places_osm_idx
  on public.outdoor_seating_places (osm_type, osm_id);

create index if not exists outdoor_seating_places_lat_lon_idx
  on public.outdoor_seating_places (lat, lon);

create index if not exists outdoor_seating_places_rating_idx
  on public.outdoor_seating_places (google_rating desc)
  where google_rating is not null;

comment on table public.outdoor_seating_places is 'Outdoor seating places imported from outdoor_seating_places.csv.';
comment on column public.outdoor_seating_places.google_price_range is 'Google price range JSON from CSV.';
comment on column public.outdoor_seating_places.google_match_distance_m is 'Distance between OSM and Google match in meters.';
comment on column public.outdoor_seating_places.google_match_name_similarity is 'Name similarity between OSM and Google match, from 0 to 1.';

-- Public read access for a frontend using the Supabase anon key.
-- Remove these lines if the table should only be readable server-side.
alter table public.outdoor_seating_places enable row level security;

drop policy if exists "Public outdoor seating read access" on public.outdoor_seating_places;
create policy "Public outdoor seating read access"
  on public.outdoor_seating_places
  for select
  using (true);
